version: "3.7"
services:

  laravel:
    build:
      context: infra
      dockerfile: dockerfiles/app.dockerfile
    container_name: laravel
    restart: unless-stopped
    working_dir: /var/www/
    env_file:
      - application/.env
    volumes:
      - ./application:/var/www/
      - ./application/supervisor/conf.d:/etc/supervisor/conf.d
    networks:
      - network_default

  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PORT: ${DB_PORT}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./infra/mysql_data:/var/lib/mysql
    networks:
      - network_default

  nginx:
    image: nginx:1.20-alpine
    container_name: nginx
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./application:/var/www
      - ./infra/nginx:/etc/nginx/templates
    networks:
      - network_default

networks:
  network_default:
    driver: bridge
